<template>
  <section class="dev">
    <aside><button v-for="c in categories" :key="c" :class="{ active: category === c }" @click="selectCategory(c)">{{ c }} <small>{{ Object.keys(registry(c)).length }}</small></button></aside>
    <div class="content">
      <div class="toolbar"><input v-model="query" placeholder="搜索 UUID、名称或描述"><button @click="createAsset">新建</button><button :disabled="!selectedId" @click="copyAsset">复制</button><button :disabled="!selectedId" @click="exportSelected">导出所选</button><button :disabled="!selectedId" @click="removeAsset">删除</button></div>
      <div class="columns">
        <div class="assets"><button v-for="item in filtered" :key="item.id" :class="{ active: selectedId === item.id }" @click="selectedId = item.id"><strong>{{ item.label }}</strong><small>{{ item.id }}</small></button></div>
        <form v-if="entry" class="editor" @submit.prevent>
          <label>UUID<input :value="selectedId" disabled></label><label>作者<input v-model="entry.author"></label><label v-if="'key' in entry">名称 / key<input v-model="entry.key"></label><label>说明<textarea v-model="entry.desc" rows="2" /></label>
          <template v-if="category === '开场白'">
            <label>主题<input v-model="entry.主题"></label><label>图标<input v-model="entry.图标"></label><label class="check"><input v-model="entry.自定义主角" type="checkbox">自定义主角</label><label class="check"><input v-model="entry.可用" type="checkbox">请求启用（引用不完整时保存会强制禁用）</label>
            <fieldset><legend>剧本引用编排</legend><label v-for="field in singleFields" :key="field">{{ field }}<select v-model="entry.内容配置[field]"><option value="">未选择</option><option v-for="(_, id) in draft.registries[field]" :key="id" :value="id">{{ assetLabel(field, id) }}</option></select></label><label v-for="field in multiFields" :key="field">{{ field }}（可多选）<select v-model="entry.内容配置[field]" multiple><option v-for="(_, id) in draft.registries[field]" :key="id" :value="id">{{ assetLabel(field, id) }}</option></select></label></fieldset>
          </template>
          <label v-else-if="category === '开场文本'">文本内容<textarea v-model="entry.data" rows="12" /></label>
          <fieldset v-else-if="category === '地图'"><legend>地图拓扑（地图节点 UUID 树）</legend><StructuredValueEditor v-model="entry.root" /></fieldset>
          <template v-else><label v-if="'type' in entry">类型<select v-if="category === '角色'" v-model="entry.type"><option>主要角色</option><option>次要角色</option></select><input v-else v-model="entry.type"></label><fieldset><legend>{{ category }}字段</legend><StructuredValueEditor v-model="entry.data" /></fieldset></template>
        </form>
      </div>
      <section class="review"><h3>保存审阅</h3><p>{{ changeSummary }}</p><ul v-if="issues.length"><li v-for="issue in issues" :key="`${issue.ownerCategory}:${issue.ownerId}:${issue.field}:${issue.targetId}`">{{ issue.ownerCategory }} {{ issue.ownerId }} 的 {{ issue.field }} 缺少 {{ issue.targetCategory }} {{ issue.targetId }}</li></ul><div><button @click="$emit('reload')">放弃草稿</button><button class="primary" @click="$emit('save')">显式保存</button></div></section>
    </div>
  </section>
</template>
<script setup lang="ts">
/* eslint-disable vue/no-mutating-props -- draft is the parent-owned editing transaction */
import { klona } from 'klona'; import { computed, ref } from 'vue';
import { deleteAsset, findReferenceIssues, type WorkshopCategory } from '../assets/model'; import { createPackage, downloadPackage } from '../assets/package';
import type { ResourceCategory, ScenarioEntry, ScenarioSourceBundle } from '../scenario/types'; import StructuredValueEditor from './StructuredValueEditor.vue';
defineEmits<{save:[];reload:[]}>();
const props=defineProps<{source:ScenarioSourceBundle;draft:ScenarioSourceBundle}>(); const categories:WorkshopCategory[]=['开场白','世界','世界经济','主线','事件','任务','势力','地图','地图节点','季节与节日','开场文本','种族','角色']; const singleFields=['开场文本','世界','地图','主线'] as const; const multiFields=['角色','世界经济','季节与节日','势力','种族','任务','事件'] as const; const category=ref<WorkshopCategory>('开场白'); const selectedId=ref(''); const query=ref('');
function registry(c:WorkshopCategory):Record<string,any>{return c==='开场白'?props.draft.scenarios:props.draft.registries[c]} const entry=computed<any>(()=>registry(category.value)[selectedId.value]); const filtered=computed(()=>Object.entries(registry(category.value)).map(([id,value]:[string,any])=>({id,label:value.key||value.desc||id})).filter(x=>`${x.id} ${x.label}`.toLowerCase().includes(query.value.toLowerCase()))); const issues=computed(()=>findReferenceIssues(props.draft)); const changeSummary=computed(()=>JSON.stringify(props.source)===JSON.stringify(props.draft)?'当前草稿没有变化。':'草稿与已保存世界书存在差异；保存将一次性写回全部配置条目。');
function selectCategory(c:WorkshopCategory){category.value=c;selectedId.value=''} function assetLabel(c:ResourceCategory,id:string){const v:any=props.draft.registries[c][id];return `${v?.key||v?.desc||id} · ${id}`} function blank():any{if(category.value==='开场白')return{author:'',key:'未命名剧本',desc:'',可用:false,主题:'',图标:'',自定义主角:false,内容配置:{开场文本:'',世界:'',角色:[],地图:'',世界经济:[],'季节与节日':[],势力:[],种族:[],主线:'',任务:[],事件:[]}} satisfies ScenarioEntry;if(category.value==='地图')return{author:'',desc:'',root:{}};if(category.value==='开场文本')return{author:'',desc:'',data:''};if(category.value==='世界'||category.value==='主线')return{author:'',desc:'',data:{}};const base:any={author:'',desc:'',key:'未命名',data:{}};if(category.value==='角色'||category.value==='种族')base.type=category.value==='角色'?'次要角色':'未分类';return base}
function createAsset(){const id=crypto.randomUUID();registry(category.value)[id]=blank();selectedId.value=id} function copyAsset(){if(!entry.value)return;const id=crypto.randomUUID();registry(category.value)[id]=klona(entry.value);selectedId.value=id} function exportSelected(){if(selectedId.value)downloadPackage(createPackage(props.draft,{[category.value]:[selectedId.value]}),`${category.value}-${selectedId.value}`)} function removeAsset(){if(!selectedId.value)return;if(category.value==='开场白'){delete props.draft.scenarios[selectedId.value];selectedId.value='';return}const impacts=deleteAsset(props.draft,category.value,selectedId.value,false);if(impacts.length&&!confirm(`该资产被 ${impacts.length} 处引用。强制删除会同步清理引用，是否继续？`))return;deleteAsset(props.draft,category.value,selectedId.value,true);selectedId.value=''}
</script>
<style scoped>.dev{display:grid;grid-template-columns:150px minmax(0,1fr);gap:14px;margin-top:18px}aside,.assets{display:flex;flex-direction:column}aside button{display:flex;justify-content:space-between;border-radius:0}.content{min-width:0}.toolbar,.columns,.review>div{display:flex;gap:8px}.toolbar input{flex:1;min-width:0;padding:8px}.columns{margin-top:10px}.assets{width:220px}.assets button{text-align:left}.assets strong,.assets small{display:block;overflow:hidden;text-overflow:ellipsis}.assets small{color:#aaa294}.editor{flex:1;display:grid;gap:9px;min-width:0}.editor label{display:grid;gap:4px}.editor input,.editor textarea,.editor select{width:100%;padding:7px;color:#eee;background:#111;border:1px solid #555}.editor .check{display:flex;align-items:center}.editor .check input{width:auto}fieldset{display:grid;gap:8px;border:1px solid #4d493f}.review{margin-top:15px;padding:14px;background:#1d1f20;border:1px solid #454239}.review ul{max-height:130px;overflow:auto;color:#e5a197}.review>div{justify-content:flex-end}.primary{background:#c7ad70;color:#17130c}@media(max-width:700px){.dev{grid-template-columns:1fr}aside{display:grid;grid-template-columns:repeat(3,1fr)}.columns{flex-direction:column}.assets{width:100%;display:grid;grid-template-columns:repeat(2,1fr)}}</style>
