<template><form class="editor" @submit.prevent>
  <section><h3>基本信息</h3><div class="grid"><label v-if="'key' in entry">运行时名称<input v-model="entry.key" required></label><label>作者<input v-model="entry.author"></label><label class="wide">说明<textarea v-model="entry.desc" rows="2" /></label></div></section>
  <section v-if="category==='开场白'"><h3>剧本设置</h3><div class="grid"><label>剧本名称<input v-model="entry.key" required></label><label>主题<input v-model="entry.主题"></label><label>图标<input v-model="entry.图标"></label><label class="check"><input v-model="entry.自定义主角" type="checkbox">允许自定义主角</label><label class="check"><input v-model="entry.可用" type="checkbox">请求启用</label></div><h3>内容编排</h3><div class="grid"><label v-for="field in singleFields" :key="field">{{field}}<select v-model="entry.内容配置[field]"><option value="">未选择</option><option v-for="(asset,id) in source.registries[field]" :key="id" :value="id">{{assetTitle(field,asset)}}</option></select></label><label v-for="field in multiFields" :key="field" class="wide">{{field}}（可多选）<select v-model="entry.内容配置[field]" multiple><option v-for="(asset,id) in source.registries[field]" :key="id" :value="id">{{assetTitle(field,asset)}}</option></select></label></div></section>
  <section v-else-if="category==='开场文本'"><h3>开场正文 <small>{{entry.data.length}} 字</small></h3><label><span class="sr-only">开场正文</span><textarea v-model="entry.data" class="prose" rows="18" /></label></section>
  <section v-else-if="category==='世界'"><h3>时间与环境</h3><div class="grid"><label v-for="field in ['时间','地点','季节','天气','地图索引']" :key="field">{{field}}<input v-model="entry.data[field]"></label><label class="check"><input v-model="entry.data.危险场景" type="checkbox">危险场景</label></div></section>
  <section v-else-if="category==='地图'"><h3>地图拓扑</h3><MapTopologyEditor v-model="entry.root" :nodes="source.registries.地图节点" /></section>
  <section v-else-if="category==='世界经济'"><h3>检索与区域</h3><StringField v-model="entry.data.名称检索词" label="名称检索词"/><StringField v-model="entry.data.区域检索词" label="区域检索词"/><h3>物价</h3><EntrySetEditor v-model="entry.data.物价" label="物价分类" :create="()=>[]"><template #entry="p"><StringListEditor :model-value="p.entry" label="商品或服务" @update:model-value="v=>setEntry(entry.data.物价,p.entryKey,v)"/></template></EntrySetEditor><h3>平均收入</h3><EntrySetEditor v-model="entry.data.平均收入" label="人群" :create="()=>''"><template #entry="p"><label>收入说明<input :value="p.entry" @input="setEntry(entry.data.平均收入,p.entryKey,($event.target as HTMLInputElement).value)"></label></template></EntrySetEditor></section>
  <section v-else-if="category==='主线'"><h3>主线条目</h3><EntrySetEditor v-model="entry.data" label="主线" :create="()=>({描述:'',警惕度:0,详细:[],'已交融的魂质':[]})"><template #entry="p"><div class="grid"><label class="wide">描述<textarea v-model="p.entry.描述"/></label><label>警惕度<input v-model.number="p.entry.警惕度" type="number"></label></div><StringField v-model="p.entry.详细" label="详细"/><StringField v-model="p.entry['已交融的魂质']" label="已交融的魂质"/></template></EntrySetEditor></section>
  <section v-else-if="category==='事件'||category==='任务'||category==='势力'||category==='季节与节日'||category==='地图节点'"><h3>{{category}}内容</h3><div class="grid"><template v-if="category==='事件'"><label v-for="f in ['描述','作用','进度']" :key="f">{{f}}<textarea v-model="entry.data[f]"/></label></template><template v-if="category==='任务'"><label v-for="f in ['描述','目标','阻碍','期望奖励']" :key="f">{{f}}<textarea v-model="entry.data[f]"/></label></template><template v-if="category==='势力'"><label class="wide">描述<textarea v-model="entry.data.描述"/></label></template><template v-if="category==='季节与节日'"><label>类型<select v-model="entry.data.类型"><option v-for="v in ['季节','节日','会议','禁忌']" :key="v">{{v}}</option></select></label><label>开始日期<input v-model="entry.data.开始日期"></label><label>截止日期<input v-model="entry.data.截止日期"></label></template><template v-if="category==='地图节点'"><label>图标<input v-model="entry.data.图标"></label><label class="wide">描述<textarea v-model="entry.data.描述"/></label><label v-for="axis in ['x','y','z']" :key="axis">方位 {{axis}}<span class="range"><input v-model.number="entry.data.方位[axis][0]" type="number"><input v-model.number="entry.data.方位[axis][1]" type="number"></span></label></template></div><StringField v-if="['势力','季节与节日','地图节点'].includes(category)" v-model="entry.data.名称检索词" label="名称检索词"/><StringField v-if="['势力','季节与节日'].includes(category)" v-model="entry.data.区域检索词" label="区域检索词"/><StringField v-if="category==='任务'" v-model="entry.data.取得成果" label="取得成果"/><StringField v-if="category==='季节与节日'" v-model="entry.data.描述" label="描述"/><StringField v-if="category==='地图节点'" v-model="entry.data.详情" label="详情"/></section>
  <section v-else-if="category==='种族'"><h3>种族特征</h3><label>种族大类<select v-model="entry.type"><option>类人种</option><option>魔物种</option></select></label><StringField v-model="entry.data" label="特征"/></section>
  <RoleEditor v-else-if="category==='角色'" v-model:entry="entry" @request-type-change="$emit('requestRoleType',$event)" />
</form></template>
<script setup lang="ts">import EntrySetEditor from'./EntrySetEditor.vue';import MapTopologyEditor from'./MapTopologyEditor.vue';import RoleEditor from'./RoleEditor.vue';import StringListEditor from'./StringListEditor.vue';import StringField from'./StringField.vue';import{assetTitle}from'../assets/presentation';import type{ScenarioSourceBundle}from'../scenario/types';import type{WorkshopCategory}from'../assets/model';defineProps<{category:WorkshopCategory;source:ScenarioSourceBundle}>();const entry=defineModel<any>('entry',{required:true});defineEmits<{requestRoleType:[type:string]}>();const singleFields=['开场文本','世界','地图','主线']as const;const multiFields=['角色','世界经济','季节与节日','势力','种族','任务','事件']as const;function setEntry(record:Record<string,unknown>,key:string,value:unknown){record[key]=value}</script>
<style scoped>.editor{display:grid;gap:14px}.editor section{padding:16px;background:#1d2123;border:1px solid #393d3f}.editor h3{margin:0 0 12px;font:500 17px Georgia,serif}.editor h3 small{color:#b8b09f;font:12px Arial}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.wide{grid-column:1/-1}.editor label{display:grid;gap:5px;color:#d8d0bf}.check{display:flex!important;align-items:center}.check input{width:auto!important}.prose{font-family:ui-monospace,monospace;line-height:1.6}.range{display:grid;grid-template-columns:1fr 1fr;gap:6px}.sr-only{position:absolute;width:1px;height:1px;overflow:hidden;clip:rect(0,0,0,0)}@media(max-width:700px){.grid{grid-template-columns:1fr}.wide{grid-column:auto}}</style>
<!-- eslint-disable vue/no-mutating-props -->
